export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const SEARCH_EVENTS = 'SEARCH_EVENTS';
export const FILTER_BY_TREND = 'FILTER_BY_TREND';